language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.8.0 on Windows" #include only Windows cause both developers only work on Windows.
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install: pip3 install --upgrade pip  # all three OSes agree about 'pip3'
# 'python' points to Python 2.7 on macOS but points to Python 3.8 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
script: python3 ./Assignment_2/index.py titles1 ignore1 require1 || python ./Assignment_2/index.py titles1 ignore1 require1
script: python3 ./Assignment_2/index.py titles2 ignore2 require2 || python ./Assignment_2/index.py titles2 ignore2 require2
script: python3 ./Assignment_2/index.py titles3 ignore3 require3 || python ./Assignment_2/index.py titles3 ignore3 require3