python3 ./main.py ./input_files/titles1.txt ./input_files/ignore1.txt ./input_files/require1.txt || python ./main.py ./input_files/titles1.txt ./input_files/ignore1.txt ./input_files/require1.txt
python3 ./main.py ./input_files/titles2.txt ./input_files/ignore2.txt ./input_files/require2.txt || python ./main.py ./input_files/titles2.txt ./input_files/ignore2.txt ./input_files/require2.txt
python3 ./main.py ./input_files/titles3.txt ./input_files/ignore3.txt ./input_files/require3.txt || python ./main.py ./input_files/titles3.txt ./input_files/ignore3.txt ./input_files/require3.txt
python3 ./main.py ./input_files/case1/ListOfFiles.in < ./input_files/inputs.txt || python ./main.py ./input_files/case1/ListOfFiles.in < ./input_files/inputs.txt
python3 ./main.py ./input_files/case2/ListOfFiles.in < ./input_files/inputs.txt || python ./main.py ./input_files/case2/ListOfFiles.in < ./input_files/inputs.txt
python3 ./main.py ./input_files/case3/ListOfFiles.in < ./input_files/inputs.txt || python ./main.py ./input_files/case3/ListOfFiles.in < ./input_files/inputs.txt
python3 ./main.py ./input_files/case4/ListOfFiles.in < ./input_files/inputs.txt || python ./main.py ./input_files/case4/ListOfFiles.in < ./input_files/inputs.txt
python3 ./main.py ./input_files/case5/ListOfFiles.in < ./input_files/inputs.txt || python ./main.py ./input_files/case5/ListOfFiles.in < ./input_files/inputs.txt
python3 ./main.py ./input_files/case6/ListOfFiles.in < ./input_files/inputs.txt || python ./main.py ./input_files/case6/ListOfFiles.in < ./input_files/inputs.txt
python3 ./main.py ./input_files/case7/ListOfFiles.in < ./input_files/inputs.txt || python ./main.py ./input_files/case7/ListOfFiles.in < ./input_files/inputs.txt